name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v0.1
    - name: Package app
      run: scala-cli .github/scripts/package.sc
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '/artifacts/**[!(*.txt),!(*.ilk)]'
        tag: ${{ github.ref }}
        file_glob: true
