name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ulc
            asset_name: ulc-pc-linux
          - os: windows-latest
            artifact_name: ulc.exe
            asset_name: ulc-pc-win32
          - os: macos-latest
            artifact_name: ulc
            asset_name: ulc-apple-darwin

    steps:
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v0.1
    - name: Package app
      run: scala-cli .github/scripts/package.sc
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /artifacts/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
